using System.Collections.ObjectModel;

namespace FreeformHelper.Application.Services;

/// <summary>
/// Represents one CAD↔Regular overlap relationship.
/// </summary>
public sealed record PadMatchLink(
    int CadPadId,
    int RegularPadId,
    double OverlapArea,
    double RegularCoverage,
    double CadCoverage);

/// <summary>
/// Holds bidirectional overlap relationships generated by geometry matching.
/// </summary>
public sealed class PadMatchResult
{
    private static readonly IReadOnlyDictionary<int, IReadOnlyList<PadMatchLink>> EmptyMap =
        new ReadOnlyDictionary<int, IReadOnlyList<PadMatchLink>>(new Dictionary<int, IReadOnlyList<PadMatchLink>>());

    public static readonly PadMatchResult Empty = new(EmptyMap, EmptyMap, PadMatchTelemetry.Empty);

    public IReadOnlyDictionary<int, IReadOnlyList<PadMatchLink>> CadToRegular { get; }
    public IReadOnlyDictionary<int, IReadOnlyList<PadMatchLink>> RegularToCad { get; }
    public IReadOnlyList<PadMatchLink> Links { get; }
    public PadMatchTelemetry Telemetry { get; }

    public PadMatchResult(
        IReadOnlyDictionary<int, IReadOnlyList<PadMatchLink>> cadToRegular,
        IReadOnlyDictionary<int, IReadOnlyList<PadMatchLink>> regularToCad,
        PadMatchTelemetry? telemetry = null)
    {
        CadToRegular = cadToRegular ?? throw new ArgumentNullException(nameof(cadToRegular));
        RegularToCad = regularToCad ?? throw new ArgumentNullException(nameof(regularToCad));
        Links = CadToRegular.Values.SelectMany(v => v).ToList();
        Telemetry = telemetry ?? PadMatchTelemetry.Empty;
    }
}

/// <summary>
/// Candidate/intersection telemetry for one Step1 geometry match run.
/// </summary>
public sealed record PadMatchTelemetry(
    int CadPadCount,
    long CandidateCellVisits,
    long BoundsIntersections,
    long PolygonIntersections,
    double CandidateCellsPerCadAverage,
    int CandidateCellsPerCadP95)
{
    public static readonly PadMatchTelemetry Empty = new(
        CadPadCount: 0,
        CandidateCellVisits: 0,
        BoundsIntersections: 0,
        PolygonIntersections: 0,
        CandidateCellsPerCadAverage: 0.0,
        CandidateCellsPerCadP95: 0);
}

