using FreeformHelper.Application.Settings;

namespace FreeformHelper.UI.ViewModels;

/// <summary>
/// This partial class of <see cref="FreeformHelperViewModel"/> contains "undo hooks"
/// for various observable properties. These hooks are partial methods generated by
/// CommunityToolkit.Mvvm and are invoked *before* a property's value changes.
/// They are used here to automatically track property changes for the undo stack.
/// </summary>
public sealed partial class FreeformHelperViewModel
{
    // --- View Toggles ---
    partial void OnShowCadChanging(bool value) => TrackUndo(ShowCad, value, v => ShowCad = v, "Toggle CAD layer");
    partial void OnShowRegularChanging(bool value) => TrackUndo(ShowRegular, value, v => ShowRegular = v, "Toggle regular grid");
    partial void OnHighlightUnmatchedChanging(bool value) => TrackUndo(HighlightUnmatched, value, v => HighlightUnmatched = v, "Toggle unmatched highlight");
    partial void OnHighlightFreeformChanging(bool value) => TrackUndo(HighlightFreeform, value, v => HighlightFreeform = v, "Toggle freeform highlight");
    partial void OnColorCadByAreaChanging(bool value) => TrackUndo(ColorCadByArea, value, v => ColorCadByArea = v, "Toggle CAD area colors");
    partial void OnShowDiffIndexOverlayChanging(bool value) => TrackUndo(ShowDiffIndexOverlay, value, v => ShowDiffIndexOverlay = v, "Toggle CAD Output FW Diff overlay");
    partial void OnShowNotchToRegularLabelsChanging(bool value) => TrackUndo(ShowNotchToRegularLabels, value, v => ShowNotchToRegularLabels = v, "Toggle To Regular labels");

    // --- Import Settings ---
    partial void OnImportOnlyClosedPolylinesChanging(bool value) => TrackUndo(ImportOnlyClosedPolylines, value, v => ImportOnlyClosedPolylines = v, "Import closed polylines");
    partial void OnImportBlockPolylinesChanging(bool value) => TrackUndo(ImportBlockPolylines, value, v => ImportBlockPolylines = v, "Import block polylines");

    // --- Line Styles ---
    partial void OnCadLineWidthChanging(decimal value) => TrackUndo(CadLineWidth, value, v => CadLineWidth = v, "CAD line width");
    partial void OnRegularLineWidthChanging(decimal value) => TrackUndo(RegularLineWidth, value, v => RegularLineWidth = v, "Regular line width");
    partial void OnHighlightStrokeWidthAdjustChanging(decimal value) => TrackUndo(HighlightStrokeWidthAdjust, value, v => HighlightStrokeWidthAdjust = v, "Highlight line width");
    partial void OnCadLineColorHexChanging(string value) => TrackUndo(CadLineColorHex, value, v => CadLineColorHex = v, "CAD line color");
    partial void OnRegularLineColorHexChanging(string value) => TrackUndo(RegularLineColorHex, value, v => RegularLineColorHex = v, "Regular line color");
    partial void OnRegularSelectedColorHexChanging(string value) => TrackUndo(RegularSelectedColorHex, value, v => RegularSelectedColorHex = v, "Regular selection color");
    partial void OnRegularSelectedFillOpacityChanging(decimal value) => TrackUndo(RegularSelectedFillOpacity, value, v => RegularSelectedFillOpacity = v, "Regular selection fill opacity");

    // --- Area Bucketing Settings ---
    partial void OnAreaBucketToleranceChanging(decimal value) => TrackUndo(AreaBucketTolerance, value, v => AreaBucketTolerance = v, "Area bucket tolerance");
    partial void OnMaxAreaBucketsChanging(decimal value) => TrackUndo(MaxAreaBuckets, value, v => MaxAreaBuckets = v, "Max area buckets");

    // --- Grid Settings ---
    partial void OnXChannelsChanging(decimal value) => TrackUndo(XChannels, value, v => XChannels = v, "X channels");
    partial void OnYChannelsChanging(decimal value) => TrackUndo(YChannels, value, v => YChannels = v, "Y channels");
    partial void OnCascadeNumChanging(decimal value) => TrackUndo(CascadeNum, value, v => CascadeNum = v, "Cascade count");
    partial void OnSelectedScanOrderChanging(ScanOrder value) => TrackUndo(SelectedScanOrder, value, v => SelectedScanOrder = v, "Scan order");
    partial void OnGridAlignmentModeChanging(GridAlignmentMode value) => TrackUndo(GridAlignmentMode, value, v => GridAlignmentMode = v, "Alignment mode");
    partial void OnGridPaddingPercentChanging(decimal value) => TrackUndo(GridPaddingPercent, value, v => GridPaddingPercent = v, "Grid padding");
    partial void OnActiveAreaWidthChanging(decimal value) => TrackUndo(ActiveAreaWidth, value, v => ActiveAreaWidth = v, "AA width");
    partial void OnActiveAreaHeightChanging(decimal value) => TrackUndo(ActiveAreaHeight, value, v => ActiveAreaHeight = v, "AA height");

    // --- Matching Settings ---
    partial void OnMatchThresholdChanging(decimal value) => TrackUndo(MatchThreshold, value, v => MatchThreshold = v, "Match threshold");
    partial void OnFreeformAxisThresholdChanging(decimal value) => TrackUndo(FreeformAxisThreshold, value, v => FreeformAxisThreshold = v, "Freeform TH");
    partial void OnEnableAutoDetectXyChanging(bool value) => TrackUndo(EnableAutoDetectXy, value, v => EnableAutoDetectXy = v, "Auto XY detect");
    partial void OnEnableFreeformEdgeSpecializationChanging(bool value) => TrackUndo(EnableFreeformEdgeSpecialization, value, v => EnableFreeformEdgeSpecialization = v, "Edge freeform");
    partial void OnCadOutputFwDiffIndexStartChanging(decimal value) => TrackUndo(CadOutputFwDiffIndexStart, value, v => CadOutputFwDiffIndexStart = v, "CAD Output FW Diff start");
    partial void OnCadOutputFwDiffAutoModeChanging(CadOutputFwDiffAutoMode value) => TrackUndo(CadOutputFwDiffAutoMode, value, v => CadOutputFwDiffAutoMode = v, "CAD Output FW Diff auto mode");
    partial void OnCadOutputFwDiffIndexAnchorCadIdChanging(decimal value) => TrackUndo(CadOutputFwDiffIndexAnchorCadId, value, v => CadOutputFwDiffIndexAnchorCadId = v, "CAD Output FW Diff anchor");

    // --- Notch Settings ---
    partial void OnEnableV21Changing(bool value) => TrackUndo(EnableV21, value, v => EnableV21 = v, "Export v2.1");
    partial void OnEnableV22Changing(bool value) => TrackUndo(EnableV22, value, v => EnableV22 = v, "Export v2.2");
    partial void OnSelectedNotchCompensationModelOptionChanging(NotchCompensationModelOption value) => TrackUndo(SelectedNotchCompensationModelOption, value, v => SelectedNotchCompensationModelOption = v, "Compensation model");
    partial void OnEnableToRegularChanging(bool value) => TrackUndo(EnableToRegular, value, v => EnableToRegular = v, "To Regular");
    partial void OnEnableToFullChanging(bool value) => TrackUndo(EnableToFull, value, v => EnableToFull = v, "To Full");
    partial void OnToFullStrictOverlapPercentChanging(decimal value) => TrackUndo(ToFullStrictOverlapPercent, value, v => ToFullStrictOverlapPercent = v, "To Full owner TH");
    partial void OnLenScaleChanging(decimal value) => TrackUndo(LenScale, value, v => LenScale = v, "LenScale");
    partial void OnNullValueChanging(decimal value) => TrackUndo(NullValue, value, v => NullValue = v, "Null value");
    partial void OnNotchThresholdQ7Changing(decimal value) => TrackUndo(NotchThresholdQ7, value, v => NotchThresholdQ7 = v, "Notch gate v2.1");
    partial void OnNotchThresholdPercentChanging(decimal value) => TrackUndo(NotchThresholdPercent, value, v => NotchThresholdPercent = v, "Notch gate TH");
    partial void OnLinkNotchThresholdsChanging(bool value) => TrackUndo(LinkNotchThresholds, value, v => LinkNotchThresholds = v, "Link notch TH");

    // --- Manual Sizing Inputs ---
    partial void OnPendingColumnWidthChanging(decimal value) => TrackUndo(PendingColumnWidth, value, v => PendingColumnWidth = v, "Manual width");
    partial void OnPendingRowHeightChanging(decimal value) => TrackUndo(PendingRowHeight, value, v => PendingRowHeight = v, "Manual height");
    partial void OnManualRowsRangeChanging(string value) => TrackUndo(ManualRowsRange, value, v => ManualRowsRange = v, "Manual rows range");
    partial void OnManualColsRangeChanging(string value) => TrackUndo(ManualColsRange, value, v => ManualColsRange = v, "Manual cols range");
}
