using Xunit;

namespace FreeformHelper.Tests;

[Collection("RuntimeQueryIpcHost")]
public sealed class RuntimeQueryCharacterizationHelpTests
{
    [Fact]
    public async Task Help_ResponseMatchesExactJsonGolden()
    {
        var response = await RuntimeQueryCharacterizationSubject.ExecuteAsync(new("1", "help"));

        Assert.True(response.Ok);
        Assert.Null(response.ErrorCode);
        Assert.Null(response.ErrorMessage);
        Assert.Equal(ExpectedJson, response.Json);
    }

    private static string ExpectedJson => string.Join(Environment.NewLine,
        "{",
        "  \"ok\": true,",
        "  \"data\": {",
        "    \"commands\": [",
        "      {",
        "        \"name\": \"help\",",
        "        \"description\": \"List supported runtime query commands and arguments.\",",
        "        \"args\": []",
        "      },",
        "      {",
        "        \"name\": \"status\",",
        "        \"description\": \"Return app/workflow/notch preview status.\",",
        "        \"args\": []",
        "      },",
        "      {",
        "        \"name\": \"selection\",",
        "        \"description\": \"Return current CAD/Regular selection.\",",
        "        \"args\": []",
        "      },",
        "      {",
        "        \"name\": \"terminal\",",
        "        \"description\": \"Return recent in-app log lines.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"tail\",",
        "            \"required\": false,",
        "            \"value\": \"1..5000\",",
        "            \"defaultValue\": 120",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"terminal-links\",",
        "        \"description\": \"Return parsed clickable links from recent terminal lines.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"tail\",",
        "            \"required\": false,",
        "            \"value\": \"1..5000\",",
        "            \"defaultValue\": 120",
        "          },",
        "          {",
        "            \"key\": \"limit\",",
        "            \"required\": false,",
        "            \"value\": \"1..2000\",",
        "            \"defaultValue\": 200",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"pad\",",
        "        \"description\": \"Return one pad snapshot (same source as Popover/Inspector).\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"cad-id\",",
        "            \"required\": false,",
        "            \"value\": \"\\u003E=0\",",
        "            \"note\": \"Use exactly one of cad-id / regular-id.\"",
        "          },",
        "          {",
        "            \"key\": \"regular-id\",",
        "            \"required\": false,",
        "            \"value\": \"\\u003E=0\",",
        "            \"note\": \"Use exactly one of cad-id / regular-id.\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"notch\",",
        "        \"description\": \"Return Notch 2.2 compensation debug payload for one CAD pad.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"cad-id\",",
        "            \"required\": true,",
        "            \"value\": \"\\u003E=0\"",
        "          },",
        "          {",
        "            \"key\": \"limit\",",
        "            \"required\": false,",
        "            \"value\": \"1..5000\",",
        "            \"defaultValue\": 200",
        "          },",
        "          {",
        "            \"key\": \"target-limit\",",
        "            \"required\": false,",
        "            \"value\": \"1..5000\",",
        "            \"defaultValue\": 120",
        "          },",
        "          {",
        "            \"key\": \"polygon-limit\",",
        "            \"required\": false,",
        "            \"value\": \"1..2000\",",
        "            \"defaultValue\": 64",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"multi-owner\",",
        "        \"description\": \"Return regular pads gated by multi-owner rule and owner CAD ids.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"cad-id\",",
        "            \"required\": true,",
        "            \"value\": \"\\u003E=0\"",
        "          },",
        "          {",
        "            \"key\": \"limit\",",
        "            \"required\": false,",
        "            \"value\": \"1..5000\",",
        "            \"defaultValue\": 200",
        "          },",
        "          {",
        "            \"key\": \"overlap-percent\",",
        "            \"required\": false,",
        "            \"value\": \"0..100\",",
        "            \"note\": \"Override strict owner overlap threshold (%) for this query only.\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"notch-stage\",",
        "        \"description\": \"Return stage-1/2/3 notch overlay polygons for one CAD pad.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"cad-id\",",
        "            \"required\": true,",
        "            \"value\": \"\\u003E=0\"",
        "          },",
        "          {",
        "            \"key\": \"polygon-limit\",",
        "            \"required\": false,",
        "            \"value\": \"1..2000\",",
        "            \"defaultValue\": 64",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"notch-validation\",",
        "        \"description\": \"Return Step 5 regular-centric validation rows (direct/incoming/outgoing).\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"regular-id\",",
        "            \"required\": true,",
        "            \"value\": \"\\u003E=0\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"load-project\",",
        "        \"description\": \"Load a project JSON file into the running app instance.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"path\",",
        "            \"required\": true,",
        "            \"value\": \"absolute or relative file path\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"run-step\",",
        "        \"description\": \"Execute workflow step (1=match, 2=freeform detect, 3=refresh notch preview, 4=index diagnostics).\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"step\",",
        "            \"required\": true,",
        "            \"value\": \"1|2|3|4\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"clear-step\",",
        "        \"description\": \"Clear workflow step result (and dependent downstream state).\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"step\",",
        "            \"required\": true,",
        "            \"value\": \"1|2|3|4|5\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"select-cad\",",
        "        \"description\": \"Programmatically select CAD pads in canvas/inspector context.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"cad-id\",",
        "            \"required\": false,",
        "            \"value\": \"\\u003E=0\",",
        "            \"note\": \"single id\"",
        "          },",
        "          {",
        "            \"key\": \"cad-ids\",",
        "            \"required\": false,",
        "            \"value\": \"comma-separated \\u003E=0\",",
        "            \"note\": \"multiple ids\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"select-regular\",",
        "        \"description\": \"Programmatically select regular pads by pad-id or index.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"regular-id\",",
        "            \"required\": false,",
        "            \"value\": \"\\u003E=0\",",
        "            \"note\": \"single regular pad id\"",
        "          },",
        "          {",
        "            \"key\": \"regular-ids\",",
        "            \"required\": false,",
        "            \"value\": \"comma-separated \\u003E=0\",",
        "            \"note\": \"multiple regular pad ids\"",
        "          },",
        "          {",
        "            \"key\": \"regular-index\",",
        "            \"required\": false,",
        "            \"value\": \"\\u003E=0\",",
        "            \"note\": \"single grid index\"",
        "          },",
        "          {",
        "            \"key\": \"regular-indices\",",
        "            \"required\": false,",
        "            \"value\": \"comma-separated \\u003E=0\",",
        "            \"note\": \"multiple grid indices\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"clear-selection\",",
        "        \"description\": \"Clear CAD/regular selection.\",",
        "        \"args\": []",
        "      },",
        "      {",
        "        \"name\": \"set-tofull\",",
        "        \"description\": \"Toggle Notch 2.2 To Full enable flag.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"enable\",",
        "            \"required\": true,",
        "            \"value\": \"true|false|1|0|on|off\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"simulation\",",
        "        \"description\": \"Return current Simulation workspace state and optionally one regular pad snapshot.\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"regular-id\",",
        "            \"required\": false,",
        "            \"value\": \"\\u003E=0\",",
        "            \"note\": \"specific regular pad to inspect in current simulation workspace\"",
        "          }",
        "        ]",
        "      },",
        "      {",
        "        \"name\": \"export-notch\",",
        "        \"description\": \"Generate Step 5 notch table and export to a CSV review or C FW file (non-interactive).\",",
        "        \"args\": [",
        "          {",
        "            \"key\": \"format\",",
        "            \"required\": true,",
        "            \"value\": \"csv (CSV review)|c-v21|c-v22\"",
        "          },",
        "          {",
        "            \"key\": \"path\",",
        "            \"required\": true,",
        "            \"value\": \"output file path\"",
        "          }",
        "        ]",
        "      }",
        "    ],",
        "    \"commonArgs\": [",
        "      {",
        "        \"key\": \"timeout-ms\",",
        "        \"required\": false,",
        "        \"value\": \"1..120000\",",
        "        \"defaultValue\": 1500",
        "      },",
        "      {",
        "        \"key\": \"json-pretty/json-compact\",",
        "        \"required\": false,",
        "        \"value\": \"output format\"",
        "      }",
        "    ],",
        "    \"examples\": [",
        "      \"freeformhelper.exe query help\",",
        "      \"freeformhelper.exe query status\",",
        "      \"freeformhelper.exe query terminal --tail 300\",",
        "      \"freeformhelper.exe query terminal-links --tail 300 --limit 300\",",
        "      \"freeformhelper.exe query pad --cad-id 4808\",",
        "      \"freeformhelper.exe query notch --cad-id 4808 --limit 400 --target-limit 128 --polygon-limit 128\",",
        "      \"freeformhelper.exe query multi-owner --cad-id 4808 --overlap-percent 1.0\",",
        "      \"freeformhelper.exe query notch-stage --cad-id 4808 --polygon-limit 96\",",
        "      \"freeformhelper.exe query notch-validation --regular-id 4978\",",
        "      \"freeformhelper.exe query load-project --path example/BOE36.35/project_3635.json\",",
        "      \"freeformhelper.exe query run-step --step 1 --timeout-ms 120000\",",
        "      \"freeformhelper.exe query select-cad --cad-id 4767\",",
        "      \"freeformhelper.exe query run-step --step 3\",",
        "      \"freeformhelper.exe query run-step --step 4\",",
        "      \"freeformhelper.exe query set-tofull --enable false\",",
        "      \"freeformhelper.exe query export-notch --format csv --path build/perf/notch_review.csv\",",
        "      \"freeformhelper.exe query export-notch --format c-v21 --path build/perf/notch_v2.1.c\",",
        "      \"freeformhelper.exe query export-notch --format c-v22 --path build/perf/notch_v2.2.c\",",
        "      \"freeformhelper.exe query simulation --regular-id 644\",",
        "      \"freeformhelper.exe query clear-step --step 3\"",
        "    ]",
        "  },",
        "  \"error\": null",
        "}");
}
