namespace FreeformHelper.Domain.Notch;

/// <summary>
/// Represents a single row of data within a <see cref="NotchTable"/>.
/// Each row contains information generated by a specific notch algorithm for a particular pad.
/// </summary>
public sealed class NotchTableRow
{
    /// <summary>
    /// Gets the <see cref="NotchAlgorithmVersion"/> that generated this row of data.
    /// </summary>
    public NotchAlgorithmVersion Version { get; }
    /// <summary>
    /// Gets the zero-based index of the IC (Integrated Circuit) this pad belongs to.
    /// </summary>
    public int IcIndex { get; }
    /// <summary>
    /// Gets the per-IC diff index assigned to the regular pad.
    /// </summary>
    public int DiffIndex { get; }
    /// <summary>
    /// Gets the unique zero-based index of the regular pad within its grid.
    /// </summary>
    public int RegularPadIndex { get; }
    /// <summary>
    /// Gets the ID of the CAD pad that was matched to the regular pad, if any.
    /// Null if no CAD pad was matched.
    /// </summary>
    public int? CadPadId { get; }
    /// <summary>
    /// Gets the array of integer values representing the specific notch data generated by the algorithm.
    /// The interpretation of these values depends on the <see cref="Version"/>.
    /// </summary>
    public int[] Values { get; }
    /// <summary>
    /// Gets strongly-typed v2.2 payload when <see cref="Version"/> is v2.2; otherwise null.
    /// </summary>
    public NotchV22Node? V22Node { get; }
    /// <summary>
    /// Gets an optional comment string associated with this notch table row, often for debugging or context.
    /// </summary>
    public string Comment { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="NotchTableRow"/> class.
    /// </summary>
    /// <param name="version">The notch algorithm version.</param>
    /// <param name="icIndex">The IC index.</param>
    /// <param name="diffIndex">The diff index.</param>
    /// <param name="regularPadIndex">The regular pad's unique index.</param>
    /// <param name="cadPadId">The ID of the matched CAD pad.</param>
    /// <param name="values">The array of generated notch values.</param>
    /// <param name="comment">An optional comment for the row.</param>
    public NotchTableRow(NotchAlgorithmVersion version, int icIndex, int diffIndex, int regularPadIndex, int? cadPadId, int[] values, string comment)
    {
        ArgumentNullException.ThrowIfNull(values);
        Version = version;
        IcIndex = icIndex;
        DiffIndex = diffIndex;
        RegularPadIndex = regularPadIndex;
        CadPadId = cadPadId;
        Values = values;
        V22Node = version == NotchAlgorithmVersion.V22 && values.Length == 7
            ? NotchV22Node.FromValues(values)
            : null;
        Comment = comment;
    }

    /// <summary>
    /// Initializes a v2.2 row with strongly-typed payload.
    /// </summary>
    public NotchTableRow(
        int icIndex,
        int diffIndex,
        int regularPadIndex,
        int? cadPadId,
        NotchV22Node v22Node,
        string comment)
    {
        ArgumentNullException.ThrowIfNull(v22Node);
        Version = NotchAlgorithmVersion.V22;
        IcIndex = icIndex;
        DiffIndex = diffIndex;
        RegularPadIndex = regularPadIndex;
        CadPadId = cadPadId;
        V22Node = v22Node;
        Values = v22Node.ToValues();
        Comment = comment;
    }
}
